xxl:
  job:
    admin:
      addresses: http://localhost:8080/xxl-job-admin
    accessToken: default_token
    executor:
      appname: xxl-job-demo
      address:
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30

spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest